version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12  # Only specify Python version
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install poetry==1.8.0  # Install the specific version of Poetry

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Building the Docker image...
      - docker buildx build --platform=linux/amd64 -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/synthetic-eeg-app:latest --push .

  build:
    commands:
      - echo Build and push completed successfully.

  post_build:
    commands:
      - echo Build process completed.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
