version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12  
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install poetry==1.8.0  
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Building the Docker image...
      - docker build -t synthetic-eeg-app .

  build:
    commands:
      - echo Tagging the Docker image...
      - docker tag synthetic-eeg-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/synthetic-eeg-app:latest
      - echo Pushing the Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/synthetic-eeg-app:latest

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
  discard-paths: yes
